### PR TITLE
fix: delete `font` from frame response `imageOptions`

### LINKED ISSUE #303: External fonts are rendered inconsistently
### Describe the bug

ref: https://github.com/wevm/frog/pull/215#issuecomment-2094011166

Looks like fonts are not applied when fetched inside frame handler.

### Link to Minimal Reproducible Example

https://github.com/dalechyn/frog-font-inconsistency

### Steps To Reproduce

_No response_

### Frog Version

0.9.2

### TypeScript Version

5.4.5

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dalechyn**
Closes https://github.com/wevm/frog/issues/303

### CODE REVIEW

File: src/types/frame.ts [hunk 1]
```diff
@@ -101,7 +101,7 @@ export type FrameResponse = {
    * @example
    * { width: 1200, height: 630 }
    */
-  imageOptions?: ImageOptions | undefined
+  imageOptions?: Omit<ImageOptions, 'fonts'> | undefined
```
Comment (tmm) [inline src/types/frame.ts]: Let's slap a `Pretty` on there so the type gets evaluated and looks nicer.

```suggestion
  imageOptions?: Pretty<Omit<ImageOptions, 'fonts'>> | undefined
```

| Before | After |
|--------|--------|
| image | image |

Comment (dalechyn) [reply src/types/frame.ts]: holy shit, what a piece of markdown art.

**Review by tmm — APPROVED** [review]
